language: cpp
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: deprecated-2017Q3
      
      env:
        - MATRIX_EVAL=""
        - INSTALL_SCRIPT="./.travis/install_platform_io.sh"
        - BUILD_SCRIPT="./.travis/script_platform_io.sh"
  
    - os: linux
      dist: trusty
      sudo: required
      
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - lcov
            
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    - os: osx
      osx_image: xcode9.3beta
      env:
        - MATRIX_EVAL=""
        - INSTALL_SCRIPT="./.travis/install_platform_io.sh"
        - BUILD_SCRIPT="./.travis/script_platform_io.sh"
        
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      addons:
        homebrew:
          packages:
            - lcov
      env:
        - COMPILER=clang++
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    - os: osx
      osx_image: xcode9.3beta
      addons:
        homebrew:
          packages:
            - lcov
      env:
        - MATRIX_EVAL=""
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
 
before_install:
    - eval "${MATRIX_EVAL}"
    - chmod -R +x ./.travis/*.sh 
 
install:
  - ${INSTALL_SCRIPT}

script:
  - ${BUILD_SCRIPT}

after_success:
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash)
